name: backend_automation
on: push
env:
  GO_VERSION: 1.18.x

jobs:
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test get-function
        run: cd resume-site/lambdacode && go test -v ./ && cd ../../
